### PR TITLE
Recurse on terminate_proc.

### PR DESCRIPTION
**Pull request by gitlost**
Hi, I had a look at this (via https://github.com/wp-cli/wp-cli/issues/4048) and it seems there's some grandchild process hanging around on Ubuntu (to do with `wp-cli-router.php`?), so recursing on terminate_proc() appears to fix it...

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@gitlost Can you uncomment the `@broken` tests so we can verify the broken tests pass?

**Comment by gitlost** [comment]
@danielbachhuber okay did that - actually had to replace them with `@require-php-5.4` tags as the `wp server` command demands it.

**Comment by danielbachhuber** [comment]
Huh, a Travis job didn't get created. Can you push one more change so we can see if the build passes?

**Comment by gitlost** [comment]
I'll try closing this and adding a new PR.

**Pull request closed without merging**
